import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Roboto, Outfit } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
});

const outfit = Outfit({
  subsets: ['latin'],
  variable: '--font-outfit',
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} ${outfit.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
