DROP TABLE IF EXISTS Matching;
DROP TABLE IF EXISTS Applications;
DROP TABLE IF EXISTS Jobs;
DROP TABLE IF EXISTS Parsed_Resume;
DROP TABLE IF EXISTS CV;
DROP TABLE IF EXISTS Kandidat;
DROP TABLE IF EXISTS Recruiter;
DROP TABLE IF EXISTS Users;